frase = input("Digite um nome e um sobrenome: ")
frase_s = frase.split()
frase_u = frase.upper()
frase_l = frase.lower()

print("\nAnalisando seu nome...")
print("Nome em maiúsculas: {}".format(frase_u))
print("Nome em minúsculas: {}".format(frase_l))
print("Total de palavras: {}".format(len(frase_s)))
print("Total de letras (primeiro nome): {}".format(len(frase_s[0])))
print("Total de letras (sobrenome): {}".format(len(frase_s[1])))
print("Total de letras: {}".format(len(frase.replace(" ", ""))))
